name: Publish Gem
on:
  push:
    branches:
      - "master"
      - "github-workflow-publish-gem-test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event name
        run: |
          echo "${{ github.event_name }}"
