name: Publish Gem

on:
  push:
    branches:
      - "github-workflow-publish-gem-test"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@master
        env:
          GEM_VERSION: 0.1.4
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          RELEASE_COMMAND: gem push biscuit-$GEM_VERSION.gem
